# Generated by Django 4.0.3 on 2022-03-01 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerid',
            name='contact_phone',
            field=models.IntegerField(default=30),
            preserve_default=False,
        ),
    ]
