# Generated by Django 4.0.3 on 2022-03-01 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_workerid_contact_phone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='workerID',
            new_name='worker',
        ),
    ]
