# Generated by Django 4.0.3 on 2022-03-01 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_rename_workerid_worker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='contact_phone',
            field=models.CharField(max_length=11),
        ),
    ]
